#cloud-config
# vim: syntax=yaml
#

#  hostname is overriden by flahs tool
hostname: willbereplaced
manage_etc_hosts: true
apt_preserve_sources_list: true


groups:
    - gpio : [pi, docker]
    - spi : [pi, docker]
    - users : [pi]
    - pi : [pi]
users:
  - name: pi                # use any user name you like
    primary-group: pi
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,gpio,spi,dialout
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB******** user@host   # more authorized public ssh keys are added in the intance specific script ./instances_data/<instance_name>/initinstance.sh 
  - name: docker
    primary-group: docker
    system: true


# Set the locale of the system
locale: en_US.UTF-8

# Set the timezone
# Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: Europe/Paris

# Update apt packages on first boot
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - vim
  - tmux
  - git
  - certbot
  - ntfs-3g


# These commands will be ran once on first boot only
runcmd:
  - 'systemctl restart avahi-daemon'
  - 'ifup wlan0'
  - 'sleep 10'
  - 'mkdir -p /home/pi/boot_data && tar -xvzf /boot/boot_secrets.tgz -C /home/pi/boot_data && chown pi -R /home/pi/boot_data'
  - su pi -c 'bash /home/pi/boot_data/initinstance.sh' && rm /boot/boot_secrets.tgz


write_files:
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=fr
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid="tofill"           # insert your SSID here
      psk="tofill"   # insert your PSK here
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf

# run on every boot
bootcmd:
# Activate WiFi interface
 - [ ifup, wlan0 ]
